/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-06-02 04:56:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;
import com.liveyc.mina.model.*;
import com.liveyc.configuration.PropsValues;
import com.liveyc.util.*;
import com.liveyc.mina.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>My JSP 'MyJsp.jsp' starting page</title>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");

    ClientMsgProtocol.getInstances().clientStart();
    Thread.sleep(5000);
	ReqRealLocation r = new ReqRealLocation();
	r.setMessageSn(1234l);
	String PLATETYPE = "01";
	String PLATENO = "皖B18678";
	String ALARMTIME = "";
	String WFDD = "340204557";
	String WFXW = "1301";
	String record = "80";
	String speedMax = "";
	String alarmTimeStr = "20150529095441";
	String ALARMID = "123";
	String url = "ftp://172.16.65.51/incoming/chenlin/images/1.jpg;ftp://172.16.65.51/incoming/chenlin/images/2.jpg";
	if (record == null || record.equals("") || record.equals("null")) {
		record = "0";
	}
	if (speedMax == null || speedMax.equals("") || speedMax.equals("null")) {
		speedMax = "0";
	}
	String picurl = "";

	if (url != null && !url.equals("")) {
		String[] urls = url.split(";");
		if (urls.length == 1) {
			String path = PropsValues.FTP_URL + WFDD + "/" + (alarmTimeStr.replaceAll("-", "")).substring(0, 8);
			String fileName = ALARMID + ".jpg";
			picurl = picurl + "/" + ALARMID + ".jpg";
			if (FtpUtil.uploadFile2(url, Integer.parseInt(PropsValues.FTP_PORT), PropsValues.FTP_USERID, PropsValues.FTP_PWD, path, fileName, urls[0])) {
				// iLog.error("上传图片成功，上传地址:" +
				// picurl);
			}

		} else {
			for (int j = 1; j <= urls.length; j++) {
				// String path =
				// PropsValues.FTP_URL
				// +"/2"+WFDD+"/"+
				// (alarmTimeStr.replaceAll("-",
				// "")).substring(0, 8);
				String fileName = ALARMID + "_" + j + ".jpg";
				// picurl = path + "/" +
				// p.get("ALARMID") + "_" + j +
				// ".jpg";
				String path = PropsValues.FTP_PATH  + WFDD + "/" + (alarmTimeStr.replaceAll("-", "")).substring(0, 8) + "/";
				System.out.println(path );
				if (FtpUtil.uploadFile2(PropsValues.FTP_URL, Integer.parseInt(PropsValues.FTP_PORT), PropsValues.FTP_USERID, PropsValues.FTP_PWD, path, fileName, urls[j - 1])) {
					// iLog.error("上传图片成功，上传地址:"
					// +
					// picurl);
				}
				if (picurl.equals("")) {

				} else {
					picurl = ";" + picurl;
				}
			}

		}
		// 违法地点
		r.setDeviceId(WFDD);
		r.setDeviceType((byte) 2);
		r.setId(String.valueOf(System.currentTimeMillis()) + String.valueOf(System.currentTimeMillis()).substring(6, 13));
		r.setDatetime(alarmTimeStr.replaceAll("-", "").trim());
		r.setMessageSn(Long.parseLong(ALARMID + ""));
		r.setMessageType(0x2101);
		r.setPicNumber((byte) url.split(";").length);
		r.setPicUrl(url);
		r.setSendTime("20150602125050");
		r.setPlateNo(PLATENO);
		r.setPlatype(PLATETYPE);
		r.setValue(Long.parseLong(record));
		r.setStandard(Long.parseLong(speedMax));
		r.setAction(WFXW);
		r.setVlength(106 + url.getBytes().length);
		r.setDataLength(115 + url.getBytes().length);
		// ClientMsgProtocol.getInstances().clientStart();
		if (ClientMsgProtocol.getInstances().isIsconenected()) {
			ClientMsgProtocol.getInstances().getConnFuture().getSession().write(r);
		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
